### ISSUE TITLE
What is this about?

### ISSUE THREAD

**Issue by arthurwolf** [Narmoistar/mnemonic-debugger#1]
Hello.

Can you give a bit more context on what the tool is, what it does, how it came to be, how to use it, etc?
What situation would lead somebody to try to "bruteforce" a blockchain seed? 

Would be extremely appreciated.
Thanks!

**Comment by Narmoistar** [comment]
Hello! This tool was created to try to help someone on Reddit who thought they had a list of words that contained a hidden complete blockchain.info mnemonic; the idea was that it could run through their list, removing invalid words, and trying all remaining combinations (in order). Ultimately it didn't pan out.
